project:
  type: website
  output-dir: docs

website:
  title: "Wildlife - Elephant"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Year_Wise_Comparison.qmd
        text: Individual Elephant Movement Patterns  
      - href: climate_data.qmd
        text: Climate Data Visualization


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

