---
title: ""
---

```{r}
#| echo: false
#| warning: false
#| message: false


library(readr)
library(dplyr)
library(plotly)
library(tidyverse)
library(crosstalk)
library(htmltools)
library(sf)
library(leaflet)

kaudulla_climate_monthly_clean <- read_csv("kaudulla_climate_monthly_clean.csv")

env_data <- kaudulla_climate_monthly_clean |>
  mutate(
    year = factor(year),

    month_name = factor(
      month_name,
      levels = c(
        "Jan", "Feb", "Mar", "Apr",
        "May", "Jun", "Jul", "Aug",
        "Sep", "Oct", "Nov", "Dec"
      ),
      ordered = TRUE
    )
  )



kaudulla_elephants_clean_imputed <- read_csv("kaudulla_elephants_clean_imputed.csv")

df_sf <- kaudulla_elephants_clean_imputed |>
  filter(!is.na(lon), !is.na(lat)) |>
  st_as_sf(
    coords = c("lon", "lat"),
    crs = 4326
  )
```

```{r}


 dark_vibrant_colors   <-  c(
    "#e6194b", "#3cb44b", "#ffe119", "#4363d8", "#f58231",
    "#911eb4", "#46f0f0", "#f032e6", "#bcf60c", "#fabebe",
    "#008080", "#e6beff", "#9a6324", "#fffac8", "#800000"
  )

color_palette1 <- colorFactor(palette = dark_vibrant_colors, domain = df_sf$name) 
 
leaflet(df_sf) |>
  addProviderTiles(providers$OpenStreetMap, group = "Street Map") |>
  addProviderTiles(providers$Esri.WorldImagery, group = "Satellite") |>
addPolylines( df_sf,
              color = "darkgray", 
              weight = 2, 
              opacity = 0.7) |>  
  addCircleMarkers( df_sf, 
    color = ~color_palette1(name),
    radius = 4,
    stroke = FALSE, fillOpacity = 0.8,
    popup = ~paste("<b>Date:</b>", datetime, "<br><b>Gender:</b>", sex)
) |>
addLegend(pal = color_palette1, values = ~name, title = "Name", position = "bottomright") |>
  addLayersControl(baseGroups = c( "Street Map","Satellite"), options = layersControlOptions(collapsed = FALSE))   
```

```{r}
#| echo: false
#| warning: false
#| message: false

env_data2 <- env_data |>
   filter(year %in% c("2023", "2024", "2025"))

make_heatmap <- function(df, var_name, title) {

  p <- ggplot(
    df,
    aes(
      x = month_name,
      y = year,
      fill = .data[[var_name]]
    )
  ) +
    geom_tile(color = "white") +
    scale_fill_viridis_c() +
    labs(title = title, x = "Month", y = "Year") +
    theme_minimal()

  ggplotly(p)
}

p_solar <- make_heatmap(env_data2, "solar_radiation", "Solar Radiation")
p_cloud <- make_heatmap(env_data2, "cloud_amount", "Cloud Amount")
p_soil <- make_heatmap(env_data2, "soil_wetness", "Soil Wetness")
p_rain <- make_heatmap(env_data2, "rainfall", "Rainfall")
p_pressure <- make_heatmap(env_data2, "pressure", "Pressure")
p_temp <- make_heatmap(env_data2, "temp_max", "Max Temperature")
p_temp_skin <- make_heatmap(env_data2, "temp_skin", "Skin Temperature")
p_wind <- make_heatmap(env_data2, "wind_speed_max", "Wind Speed")
p_wind_corrected <- make_heatmap(env_data2, "wind_speed_corrected", "Corrected Wind Speed")


p_solar

p_cloud

p_soil

p_rain

p_pressure

p_temp

p_temp_skin

p_wind

p_wind_corrected

```

```{r}

```
